version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "4000:4000"
    environment:
      # Add these for better Eureka integration
      - SPRING_APPLICATION_NAME=api-gateway

    networks:
      - microservices-network


networks:
  microservices-network:
    external: true